// for Login Api Action type

export const LOG_IN_INIT = "LOG_IN_INIT";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAIL = "LOG_IN_FAIL";

export const SIGN_UP_INIT = "SIGN_UP_INIT";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";

export const USER_ROLES_INIT = "USER_ROLES_INIT";
export const USER_ROLES_SUCCESS = "USER_ROLES_SUCCESS";
export const USER_ROLES_FAIL = "USER_ROLES_FAIL";

export const SIGN_OUT = "SIGN_OUT";

// Refresh Token
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_FAIL = "REFRESH_TOKEN_FAIL";

// for get all corporate Categories dropdown
export const GET_ALL_CORPORATE_CATEGORIES_INIT =
  "GET_ALL_CORPORATE_CATEGORIES_INIT";
export const GET_ALL_CORPORATE_CATEGORIES_SUCCESS =
  "GET_ALL_CORPORATE_CATEGORIES_SUCCESS";
export const GET_ALL_CORPORATE_CATEGORIES_FAIL =
  "GET_ALL_CORPORATE_CATEGORIES_FAIL";

// For get Bank User Login History Api
export const GET_BANK_USER_LOGIN_INIT = "GET_BANK_USER_LOGIN_INIT";
export const GET_BANK_USER_LOGIN_SUCCESS = "GET_BANK_USER_LOGIN_SUCCESS";
export const GET_BANK_USER_LOGIN_FAIL = "GET_BANK_USER_LOGIN_FAIL";

// Search Company User Login History
export const SEARCH_COMPANY_USER_LOGIN_INIT = "SEARCH_COMPANY_USER_LOGIN_INIT";
export const SEARCH_COMPANY_USER_LOGIN_SUCCESS =
  "SEARCH_COMPANY_USER_LOGIN_SUCCESS";
export const SEARCH_COMPANY_USER_LOGIN_FAIL = "SEARCH_COMPANY_USER_LOGIN_FAIL";

// Search Bank User Login History
export const SEARCH_BANK_USER_LOGIN_INIT = "SEARCH_BANK_USER_LOGIN_INIT";
export const SEARCH_BANK_USER_LOGIN_SUCCESS = "SEARCH_BANK_USER_LOGIN_SUCCESS";
export const SEARCH_BANK_USER_LOGIN_FAIL = "SEARCH_BANK_USER_LOGIN_FAIL";

// get all corporate user System admin api
export const GET_ALL_CORPORATE_USER_INIT = "GET_ALL_CORPORATE_USER_INIT";
export const GET_ALL_CORPORATE_USER_SUCCESS = "GET_ALL_CORPORATE_USER_SUCCESS";
export const GET_ALL_CORPORATE_USER_FAIL = "GET_ALL_CORPORATE_USER_FAIL";

// seacrh corporate user system Admin api
export const SEARCH_CORPORATE_USER_INIT = "SEARCH_CORPORATE_USER_INIT";
export const SEARCH_CORPORATE_USER_SUCCESS = "SEARCH_CORPORATE_USER_SUCCESS";
export const SEARCH_CORPORATE_USER_FAIL = "SEARCH_CORPORATE_USER_FAIL";

// get all User status API in Customer Modal View
export const GET_ALL_USER_STATUS_API_INIT = "GET_ALL_USER_STATUS_API_INIT";
export const GET_ALL_USER_STATUS_API_SUCCESS =
  "GET_ALL_USER_STATUS_API_SUCCESS";
export const GET_ALL_USER_STATUS_API_FAIL = "GET_ALL_USER_STATUS_API_FAIL";

//For Get All Corporate ERM Company dropdown Api
export const GET_ALL_CORPORATES_COMPANY_INIT =
  "GET_ALL_CORPORATES_COMPANY_INIT";
export const GET_ALL_CORPORATES_COMPANY_SUCCESS =
  "GET_ALL_CORPORATES_COMPANY_SUCCESS";
export const GET_ALL_CORPORATES_COMPANY_FAIL =
  "GET_ALL_CORPORATES_COMPANY_FAIL";

// For Update Corporate User Api
export const UPDATE_CORPORATE_USER_INIT = "UPDATE_CORPORATE_USER_INIT";
export const UPDATE_CORPORATE_USER_SUCCESS = "UPDATE_CORPORATE_USER_SUCCESS";
export const UPDATE_CORPORATE_USER_FAIL = "UPDATE_CORPORATE_USER_FAIL";

//for Get All Bank User API
export const GET_ALL_BANK_CORPORATE_INIT = "GET_ALL_BANK_CORPORATE_INIT";
export const GET_ALL_BANK_CORPORATE_SUCCESS = "GET_ALL_BANK_CORPORATE_SUCCESS";
export const GET_ALL_BANK_CORPORATE_FAIL = "GET_ALL_BANK_CORPORATE_FAIL";

// for all nature Business Type
export const GET_ALL_NATURE_BUSINESS_INIT = "GET_ALL_NATURE_BUSINESS_INIT";
export const GET_ALL_NATURE_BUSINESS_SUCCESS =
  "GET_ALL_NATURE_BUSINESS_SUCCESS";
export const GET_ALL_NATURE_BUSINESS_FAIL = "GET_ALL_NATURE_BUSINESS_FAIL";

// for get all corporate name by bank ID for company dropdown
export const GET_ALL_CORPORATE_NAME_BY_BANK_INIT =
  "GET_ALL_CORPORATE_NAME_BY_BANK_INIT";
export const GET_ALL_CORPORATE_NAME_BY_BANK_SUCCESS =
  "GET_ALL_CORPORATE_NAME_BY_BANK_SUCCESS";
export const GET_ALL_CORPORATE_NAME_BY_BANK_FAIL =
  "GET_ALL_CORPORATE_NAME_BY_BANK_FAIL";

// for get all bank user in security admin on bank user list page to show data in table
export const GET_ALL_BANK_USER_INIT = "GET_ALL_BANK_USER_INIT";
export const GET_ALL_BANK_USER_SUCCESS = "GET_ALL_BANK_USER_SUCCESS";
export const GET_ALL_BANK_USER_FAIL = "GET_ALL_BANK_USER_FAIL";

// for search bank user list API
export const SEARCH_BANK_USER_INIT = "SEARCH_BANK_USER_INIT";
export const SEARCH_BANK_USER_SUCCESS = "SEARCH_BANK_USER_SUCCESS";
export const SEARCH_BANK_USER_FAIL = "SEARCH_BANK_USER_FAIL";

// for update user by user ID on bank user list page
export const UPDATE_USER_BY_USERID_INIT = "UPDATE_USER_BY_USERID_INIT";
export const UPDATE_USER_BY_USERID_SUCCESS = "UPDATE_USER_BY_USERID_SUCCESS";
export const UPDATE_USER_BY_USERID_FAIL = "UPDATE_USER_BY_USERID_FAIL";

// for download corporate User login History Excel File
export const DOWNLOAD_EXCEL_CORPORATE_FILE_INIT =
  "DOWNLOAD_EXCEL_CORPORATE_FILE_INIT";

//for download Report Loader Api
export const DOWNLOAD_REPORT_INIT = "DOWNLOAD_REPORT_INIT";

//for download something went wrong
export const SOME_THING_WENT_WRONG = "SOME_THING_WENT_WRONG";

// for download corporate User login History Excel File
export const DOWNLOAD_EXCEL_BANK_FILE_INIT = "DOWNLOAD_EXCEL_BANK_FILE_INIT";

// for Upload Counter party Excel file
export const COUNTER_PARTY_LIMIT_EXCEL_FILE_INIT =
  "COUNTER_PARTY_LIMIT_EXCEL_FILE_INIT";
export const COUNTER_PARTY_LIMIT_EXCEL_FILE_SUCCESS =
  "COUNTER_PARTY_LIMIT_EXCEL_FILE_SUCCESS";
export const COUNTER_PARTY_LIMIT_EXCEL_FILE_FAIL =
  "COUNTER_PARTY_LIMIT_EXCEL_FILE_FAIL";
export const RESET_COUNTER_PART_FILE_UPLOAD = "RESET_COUNTER_PART_FILE_UPLOAD";

//GET ALL CORPORATES
export const GET_ALL_CORPORATES_INIT = "GET_ALL_CORPORATES_INIT";
export const GET_ALL_CORPORATES_SUCCESS = "GET_ALL_CORPORATES_SUCCESS";
export const GET_ALL_CORPORATES_FAIL = "GET_ALL_CORPORATES_FAIL";

//UpdateCorporateMapping
export const UPDATE_CORPORATE_MAPPING_INIT = "UPDATE_CORPORATE_MAPPING_INIT";
export const UPDATE_CORPORATE_MAPPING_SUCCESS =
  "UPDATE_CORPORATE_MAPPING_SUCCESS";
export const UPDATE_CORPORATE_MAPPING_FAIL = "UPDATE_CORPORATE_MAPPING_FAIL";

//CategoryADD

export const ADD_CATEGORY_INIT = "ADD_CATEGORY_INIT";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL";

//Delete Category
export const DELETE_CATEGORY_INIT = "DELETE_CATEGORY_INIT";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILED = "DELETE_CATEGORY_FAILED";

// Download Counter Party modal Report
export const DOWNLOAD_COUNTER_PARTY_REPORT_INIT =
  "DOWNLOAD_COUNTER_PARTY_REPORT_INIT";

// ********************************************BOP New APis*********************************************

//Add Bank User Modal
export const ADD_BANK_USER_MODAL = "ADD_BANK_USER_MODAL";
// Edit Corporate Modal
export const EDIT_CORPORATE_MODAL = "EDIT_CORPORATE_MODAL";
// Delete Corporate Modal
export const DELETE_CORPORATE_MODAL = "DELETE_CORPORATE_MODAL";
// UserDetails Corporate Modal
export const USER_DETAILS_CORPORATE_MODAL = "USER_DETAILS_CORPORATE_MODAL";
// Add Category Modal
export const ADD_CATEGORY_MODAL = "ADD_CATEGORY_MODAL";
// Corporate PlusIcon Modal Add Company
export const CORPORATE_PLUS_ICON_MODAL = "CORPORATE_PLUS_ICON_MODAL";
// Corporate Edit Company Modal
export const CORPORATE_EDIT_COMPANY_MODAL = "CORPORATE_EDIT_COMPANY_MODAL";
//  Edit Bank User Modal
export const EDIT_BANK_USER_MODAL = "EDIT_BANK_USER_MODAL";
//  Edit Modal Trade Access Manangement
export const EDIT_TRADE_ACCESS_MANAGMENT_MODAL =
  "EDIT_TRADE_ACCESS_MANAGMENT_MODAL";

//Send Email For Reset Password
export const SEND_EMAIL_RESET_PASSWORD_INIT = "SEND_EMAIL_RESET_PASSWORD_INIT";
export const SEND_EMAIL_RESET_PASSWORD_SUCCESS =
  "SEND_EMAIL_RESET_PASSWORD_SUCCESS";
export const SEND_EMAIL_RESET_PASSWORD_FAIL = "SEND_EMAIL_RESET_PASSWORD_FAIL";

//Create New Corporate
export const CREATE_NEW_CORPORATE_INIT = "CREATE_NEW_CORPORATE_INIT";
export const CREATE_NEW_CORPORATE_SUCCESS = "CREATE_NEW_CORPORATE_SUCCESS";
export const CREATE_NEW_CORPORATE_FAIL = "CREATE_NEW_CORPORATE_FAIL";

//Update Corporate By Corporate By CorporateID
export const UPDATE_CORPORATE_BY_CORPORATEID_INIT =
  "UPDATE_CORPORATE_BY_CORPORATEID_INIT";
export const UPDATE_CORPORATE_BY_CORPORATEID_SUCCESS =
  "UPDATE_CORPORATE_BY_CORPORATEID_SUCCESS";
export const UPDATE_CORPORATE_BY_CORPORATEID_FAIL =
  "UPDATE_CORPORATE_BY_CORPORATEID_FAIL";

//Add Branch
export const ADD_BRANCH_INIT = "ADD_BRANCH_INIT";
export const ADD_BRANCH_SUCCESS = "ADD_BRANCH_SUCCESS";
export const ADD_BRANCH_FAIL = "ADD_BRANCH_FAIL";

//Update Branch
export const UPDATE_BRANCH_INIT = "UPDATE_BRANCH_INIT";
export const UPDATE_BRANCH_SUCCESS = "UPDATE_BRANCH_SUCCESS";
export const UPDATE_BRANCH_FAIL = "UPDATE_BRANCH_FAIL";

//Get All Branches
export const GET_ALL_BRANCHES_INIT = "GET_ALL_BRANCHES_INIT";
export const GET_ALL_BRANCHES_SUCCESS = "GET_ALL_BRANCHES_SUCCESS";
export const GET_ALL_BRANCHES_FAIL = "GET_ALL_BRANCHES_FAIL";

//Creat Bank User Request
export const CREATE_BANK_USER_REQUEST_INIT = "CREATE_BANK_USER_REQUEST_INIT";
export const CREATE_BANK_USER_REQUEST_SUCCESS =
  "CREATE_BANK_USER_REQUEST_SUCCESS";
export const CREATE_BANK_USER_REQUEST_FAIL = "CREATE_BANK_USER_REQUEST_FAIL";

//Create Bulk Bank User Request
export const CREATE_BULK_BANK_USER_REQUEST_INIT =
  "CREATE_BULK_BANK_USER_REQUEST_INIT";
export const CREATE_BULK_BANK_USER_REQUEST_SUCCESS =
  "CREATE_BULK_BANK_USER_REQUEST_SUCCESS";
export const CREATE_BULK_BANK_USER_REQUEST_FAIL =
  "CREATE_BULK_BANK_USER_REQUEST_FAIL";

//Create Corporate User Reqeust
export const CREATE_CORPORATE_USER_REQUEST_INIT =
  "CREATE_CORPORATE_USER_REQUEST_INIT";
export const CREATE_CORPORATE_USER_REQUEST_SUCCESS =
  "CREATE_CORPORATE_USER_REQUEST_SUCCESS";
export const CREATE_CORPORATE_USER_REQUEST_FAIL =
  "CREATE_CORPORATE_USER_REQUEST_FAIL";

//Create Bulk Corporate User Request

export const CREATE_BULK_CORPORATE_USER_REQUEST_INIT =
  "CREATE_BULK_CORPORATE_USER_REQUEST_INIT";
export const CREATE_BULK_CORPORATE_USER_REQUEST_SUCCESS =
  "CREATE_BULK_CORPORATE_USER_REQUEST_SUCCESS";
export const CREATE_BULK_CORPORATE_USER_REQUEST_FAIL =
  "CREATE_BULK_CORPORATE_USER_REQUEST_FAIL";

//Bank Users BankUserListS
export const BANK_USERS_BANK_LIST_INIT = "BANK_USERS_BANK_LIST_INIT";
export const BANK_USERS_BANK_LIST_SUCCESS = "BANK_USERS_BANK_LIST_SUCCESS";
export const BANK_USERS_BANK_LIST_FAIL = "BANK_USERS_BANK_LIST_FAIL";

//Corporate Users Bulk List
export const CORPORATE_USERS_BULK_LIST_INIT = "CORPORATE_USERS_BULK_LIST_INIT";
export const CORPORATE_USERS_BULK_LIST_SUCCESS =
  "CORPORATE_USERS_BULK_LIST_SUCCESS";
export const CORPORATE_USERS_BULK_LIST_FAIL = "CORPORATE_USERS_BULK_LIST_FAIL";

//Search Corporate Users
export const SEARCH_CORPORATE_USERS_INIT = "SEARCH_CORPORATE_USERS_INIT";
export const SEARCH_CORPORATE_USERS_SUCCESS = "SEARCH_CORPORATE_USERS_SUCCESS";
export const SEARCH_CORPORATE_USERS_FAIL = "SEARCH_CORPORATE_USERS_FAIL";
