// for Login Api Action type

export const LOG_IN_INIT = "LOG_IN_INIT";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAIL = "LOG_IN_FAIL";

export const SIGN_UP_INIT = "SIGN_UP_INIT";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";

export const USER_ROLES_INIT = "USER_ROLES_INIT";
export const USER_ROLES_SUCCESS = "USER_ROLES_SUCCESS";
export const USER_ROLES_FAIL = "USER_ROLES_FAIL";

export const SIGN_OUT = "SIGN_OUT";

// Refresh Token
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_FAIL = "REFRESH_TOKEN_FAIL";

// for get all corporate Categories dropdown
export const GET_ALL_CORPORATE_CATEGORIES_INIT =
  "GET_ALL_CORPORATE_CATEGORIES_INIT";
export const GET_ALL_CORPORATE_CATEGORIES_SUCCESS =
  "GET_ALL_CORPORATE_CATEGORIES_SUCCESS";
export const GET_ALL_CORPORATE_CATEGORIES_FAIL =
  "GET_ALL_CORPORATE_CATEGORIES_FAIL";

// For get Bank User Login History Api
export const GET_BANK_USER_LOGIN_INIT = "GET_BANK_USER_LOGIN_INIT";
export const GET_BANK_USER_LOGIN_SUCCESS = "GET_BANK_USER_LOGIN_SUCCESS";
export const GET_BANK_USER_LOGIN_FAIL = "GET_BANK_USER_LOGIN_FAIL";

// Search Company User Login History
export const SEARCH_COMPANY_USER_LOGIN_INIT = "SEARCH_COMPANY_USER_LOGIN_INIT";
export const SEARCH_COMPANY_USER_LOGIN_SUCCESS =
  "SEARCH_COMPANY_USER_LOGIN_SUCCESS";
export const SEARCH_COMPANY_USER_LOGIN_FAIL = "SEARCH_COMPANY_USER_LOGIN_FAIL";

// Search Bank User Login History
export const SEARCH_BANK_USER_LOGIN_INIT = "SEARCH_BANK_USER_LOGIN_INIT";
export const SEARCH_BANK_USER_LOGIN_SUCCESS = "SEARCH_BANK_USER_LOGIN_SUCCESS";
export const SEARCH_BANK_USER_LOGIN_FAIL = "SEARCH_BANK_USER_LOGIN_FAIL";

// get all corporate user System admin api
export const GET_ALL_CORPORATE_USER_INIT = "GET_ALL_CORPORATE_USER_INIT";
export const GET_ALL_CORPORATE_USER_SUCCESS = "GET_ALL_CORPORATE_USER_SUCCESS";
export const GET_ALL_CORPORATE_USER_FAIL = "GET_ALL_CORPORATE_USER_FAIL";

// // seacrh corporate user system Admin api
// export const SEARCH_CORPORATE_USER_INIT = "SEARCH_CORPORATE_USER_INIT";
// export const SEARCH_CORPORATE_USER_SUCCESS = "SEARCH_CORPORATE_USER_SUCCESS";
// export const SEARCH_CORPORATE_USER_FAIL = "SEARCH_CORPORATE_USER_FAIL";

// get all User status API in Customer Modal View
export const GET_ALL_USER_STATUS_API_INIT = "GET_ALL_USER_STATUS_API_INIT";
export const GET_ALL_USER_STATUS_API_SUCCESS =
  "GET_ALL_USER_STATUS_API_SUCCESS";
export const GET_ALL_USER_STATUS_API_FAIL = "GET_ALL_USER_STATUS_API_FAIL";

//For Get All Corporate ERM Company dropdown Api
export const GET_ALL_CORPORATES_COMPANY_INIT =
  "GET_ALL_CORPORATES_COMPANY_INIT";
export const GET_ALL_CORPORATES_COMPANY_SUCCESS =
  "GET_ALL_CORPORATES_COMPANY_SUCCESS";
export const GET_ALL_CORPORATES_COMPANY_FAIL =
  "GET_ALL_CORPORATES_COMPANY_FAIL";

// For Update Corporate User Api
export const UPDATE_CORPORATE_USER_INIT = "UPDATE_CORPORATE_USER_INIT";
export const UPDATE_CORPORATE_USER_SUCCESS = "UPDATE_CORPORATE_USER_SUCCESS";
export const UPDATE_CORPORATE_USER_FAIL = "UPDATE_CORPORATE_USER_FAIL";

//for Get All Bank User API
export const GET_ALL_BANK_CORPORATE_INIT = "GET_ALL_BANK_CORPORATE_INIT";
export const GET_ALL_BANK_CORPORATE_SUCCESS = "GET_ALL_BANK_CORPORATE_SUCCESS";
export const GET_ALL_BANK_CORPORATE_FAIL = "GET_ALL_BANK_CORPORATE_FAIL";

// for all nature Business Type
export const GET_ALL_NATURE_OF_BUSINESS_INIT =
  "GET_ALL_NATURE_OF_BUSINESS_INIT";
export const GET_ALL_NATURE_OF_BUSINESS_SUCCESS =
  "GET_ALL_NATURE_OF_BUSINESS_SUCCESS";
export const GET_ALL_NATURE_OF_BUSINESS_FAIL =
  "GET_ALL_NATURE_OF_BUSINESS_FAIL";

// for get all corporate name by bank ID for company dropdown
export const GET_ALL_CORPORATE_NAME_BY_BANK_INIT =
  "GET_ALL_CORPORATE_NAME_BY_BANK_INIT";
export const GET_ALL_CORPORATE_NAME_BY_BANK_SUCCESS =
  "GET_ALL_CORPORATE_NAME_BY_BANK_SUCCESS";
export const GET_ALL_CORPORATE_NAME_BY_BANK_FAIL =
  "GET_ALL_CORPORATE_NAME_BY_BANK_FAIL";

// for get all bank user in System admin on bank user list page to show data in table
export const GET_ALL_BANK_USERS_INIT = "GET_ALL_BANK_USERS_INIT";
export const GET_ALL_BANK_USERS_SUCCESS = "GET_ALL_BANK_USERS_SUCCESS";
export const GET_ALL_BANK_USERS_FAIL = "GET_ALL_BANK_USERS_FAIL";

// for search bank user list API
export const SEARCH_BANK_USER_INIT = "SEARCH_BANK_USER_INIT";
export const SEARCH_BANK_USER_SUCCESS = "SEARCH_BANK_USER_SUCCESS";
export const SEARCH_BANK_USER_FAIL = "SEARCH_BANK_USER_FAIL";

// for update user by user ID on bank user list page
export const UPDATE_USER_BY_USERID_INIT = "UPDATE_USER_BY_USERID_INIT";
export const UPDATE_USER_BY_USERID_SUCCESS = "UPDATE_USER_BY_USERID_SUCCESS";
export const UPDATE_USER_BY_USERID_FAIL = "UPDATE_USER_BY_USERID_FAIL";

// for download corporate User login History Excel File
export const DOWNLOAD_EXCEL_CORPORATE_FILE_INIT =
  "DOWNLOAD_EXCEL_CORPORATE_FILE_INIT";

//for download Report Loader Api
export const DOWNLOAD_REPORT_INIT = "DOWNLOAD_REPORT_INIT";

//for download something went wrong
export const SOME_THING_WENT_WRONG = "SOME_THING_WENT_WRONG";

// for download corporate User login History Excel File
export const DOWNLOAD_EXCEL_BANK_FILE_INIT = "DOWNLOAD_EXCEL_BANK_FILE_INIT";

// for Upload Counter party Excel file
export const COUNTER_PARTY_LIMIT_EXCEL_FILE_INIT =
  "COUNTER_PARTY_LIMIT_EXCEL_FILE_INIT";
export const COUNTER_PARTY_LIMIT_EXCEL_FILE_SUCCESS =
  "COUNTER_PARTY_LIMIT_EXCEL_FILE_SUCCESS";
export const COUNTER_PARTY_LIMIT_EXCEL_FILE_FAIL =
  "COUNTER_PARTY_LIMIT_EXCEL_FILE_FAIL";
export const RESET_COUNTER_PART_FILE_UPLOAD = "RESET_COUNTER_PART_FILE_UPLOAD";

//GET ALL CORPORATES
export const GET_ALL_CORPORATES_INIT = "GET_ALL_CORPORATES_INIT";
export const GET_ALL_CORPORATES_SUCCESS = "GET_ALL_CORPORATES_SUCCESS";
export const GET_ALL_CORPORATES_FAIL = "GET_ALL_CORPORATES_FAIL";

//UpdateCorporateMapping
export const UPDATE_CORPORATE_MAPPING_INIT = "UPDATE_CORPORATE_MAPPING_INIT";
export const UPDATE_CORPORATE_MAPPING_SUCCESS =
  "UPDATE_CORPORATE_MAPPING_SUCCESS";
export const UPDATE_CORPORATE_MAPPING_FAIL = "UPDATE_CORPORATE_MAPPING_FAIL";

//CategoryADD

export const ADD_CATEGORY_INIT = "ADD_CATEGORY_INIT";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL";

//Delete Category
export const DELETE_CATEGORY_INIT = "DELETE_CATEGORY_INIT";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILED = "DELETE_CATEGORY_FAILED";

// Download Counter Party modal Report
export const DOWNLOAD_COUNTER_PARTY_REPORT_INIT =
  "DOWNLOAD_COUNTER_PARTY_REPORT_INIT";

// ********************************************BOP New APis*********************************************

//Add Bank User Modal
export const ADD_BANK_USER_MODAL = "ADD_BANK_USER_MODAL";
// Edit Corporate Modal
export const EDIT_CORPORATE_MODAL = "EDIT_CORPORATE_MODAL";
// Delete Corporate Modal
export const DELETE_CORPORATE_MODAL = "DELETE_CORPORATE_MODAL";
// UserDetails Corporate Modal
export const USER_DETAILS_CORPORATE_MODAL = "USER_DETAILS_CORPORATE_MODAL";
// Add Category Modal
export const ADD_CATEGORY_MODAL = "ADD_CATEGORY_MODAL";
// Corporate PlusIcon Modal Add Company
export const CORPORATE_PLUS_ICON_MODAL = "CORPORATE_PLUS_ICON_MODAL";
// Corporate Edit Company Modal
export const CORPORATE_EDIT_COMPANY_MODAL = "CORPORATE_EDIT_COMPANY_MODAL";
//  Edit Bank User Modal
export const EDIT_BANK_USER_MODAL = "EDIT_BANK_USER_MODAL";
//  Edit Modal Trade Access Manangement
export const EDIT_TRADE_ACCESS_MANAGMENT_MODAL =
  "EDIT_TRADE_ACCESS_MANAGMENT_MODAL";

//*************************************Global States for Confirmation Modal****************************by Yunus

// Delete Corporate Modal
export const ADD_BANK_USER_CONFIRMATION_MODAL =
  "ADD_BANK_USER_CONFIRMATION_MODAL";

// Confirmation Modal
export const CONFIRMATION_MODAL = "CONFIRMATION_MODAL";

export const TRADE_COUNT_COMMENT_MODAL = "TRADE_COUNT_COMMENT_MODAL";

export const BULK_UPLOAD_BANK_MODAL = "BULK_UPLOAD_BANK_MODAL";

// *******************************     END      ********************************************

//Send Email For Reset Password
export const SEND_EMAIL_RESET_PASSWORD_INIT = "SEND_EMAIL_RESET_PASSWORD_INIT";
export const SEND_EMAIL_RESET_PASSWORD_SUCCESS =
  "SEND_EMAIL_RESET_PASSWORD_SUCCESS";
export const SEND_EMAIL_RESET_PASSWORD_FAIL = "SEND_EMAIL_RESET_PASSWORD_FAIL";

//Create New Corporate
export const CREATE_NEW_CORPORATE_INIT = "CREATE_NEW_CORPORATE_INIT";
export const CREATE_NEW_CORPORATE_SUCCESS = "CREATE_NEW_CORPORATE_SUCCESS";
export const CREATE_NEW_CORPORATE_FAIL = "CREATE_NEW_CORPORATE_FAIL";

//Update Corporate By Corporate By CorporateID
export const UPDATE_CORPORATE_BY_CORPORATEID_INIT =
  "UPDATE_CORPORATE_BY_CORPORATEID_INIT";
export const UPDATE_CORPORATE_BY_CORPORATEID_SUCCESS =
  "UPDATE_CORPORATE_BY_CORPORATEID_SUCCESS";
export const UPDATE_CORPORATE_BY_CORPORATEID_FAIL =
  "UPDATE_CORPORATE_BY_CORPORATEID_FAIL";

//Add Branch
export const ADD_BRANCH_INIT = "ADD_BRANCH_INIT";
export const ADD_BRANCH_SUCCESS = "ADD_BRANCH_SUCCESS";
export const ADD_BRANCH_FAIL = "ADD_BRANCH_FAIL";

//Update Branch
export const UPDATE_BRANCH_INIT = "UPDATE_BRANCH_INIT";
export const UPDATE_BRANCH_SUCCESS = "UPDATE_BRANCH_SUCCESS";
export const UPDATE_BRANCH_FAIL = "UPDATE_BRANCH_FAIL";

//Get All Branches
export const GET_ALL_BRANCHES_INIT = "GET_ALL_BRANCHES_INIT";
export const GET_ALL_BRANCHES_SUCCESS = "GET_ALL_BRANCHES_SUCCESS";
export const GET_ALL_BRANCHES_FAIL = "GET_ALL_BRANCHES_FAIL";

//Get All Branches
export const GET_ALL_CATEGORIES_INIT = "GET_ALL_CATEGORIES_INIT";
export const GET_ALL_CATEGORIES_SUCCESS = "GET_ALL_CATEGORIES_SUCCESS";
export const GET_ALL_CATEGORIES_FAIL = "GET_ALL_CATEGORIES_FAIL";

//Creat Bank User Request
export const CREATE_BANK_USER_REQUEST_INIT = "CREATE_BANK_USER_REQUEST_INIT";
export const CREATE_BANK_USER_REQUEST_SUCCESS =
  "CREATE_BANK_USER_REQUEST_SUCCESS";
export const CREATE_BANK_USER_REQUEST_FAIL = "CREATE_BANK_USER_REQUEST_FAIL";

//Create Bulk Bank User Request
export const CREATE_BULK_BANK_USER_REQUEST_INIT =
  "CREATE_BULK_BANK_USER_REQUEST_INIT";
export const CREATE_BULK_BANK_USER_REQUEST_SUCCESS =
  "CREATE_BULK_BANK_USER_REQUEST_SUCCESS";
export const CREATE_BULK_BANK_USER_REQUEST_FAIL =
  "CREATE_BULK_BANK_USER_REQUEST_FAIL";

//Create Corporate User Reqeust
export const CREATE_CORPORATE_USER_REQUEST_INIT =
  "CREATE_CORPORATE_USER_REQUEST_INIT";
export const CREATE_CORPORATE_USER_REQUEST_SUCCESS =
  "CREATE_CORPORATE_USER_REQUEST_SUCCESS";
export const CREATE_CORPORATE_USER_REQUEST_FAIL =
  "CREATE_CORPORATE_USER_REQUEST_FAIL";

//Create Bulk Corporate User Request

export const CREATE_BULK_CORPORATE_USER_REQUEST_INIT =
  "CREATE_BULK_CORPORATE_USER_REQUEST_INIT";
export const CREATE_BULK_CORPORATE_USER_REQUEST_SUCCESS =
  "CREATE_BULK_CORPORATE_USER_REQUEST_SUCCESS";
export const CREATE_BULK_CORPORATE_USER_REQUEST_FAIL =
  "CREATE_BULK_CORPORATE_USER_REQUEST_FAIL";

//Bank Users BankUserListS
export const BANK_USERS_BANK_LIST_INIT = "BANK_USERS_BANK_LIST_INIT";
export const BANK_USERS_BANK_LIST_SUCCESS = "BANK_USERS_BANK_LIST_SUCCESS";
export const BANK_USERS_BANK_LIST_FAIL = "BANK_USERS_BANK_LIST_FAIL";

//Corporate Users Bulk List
export const CORPORATE_USERS_BULK_LIST_INIT = "CORPORATE_USERS_BULK_LIST_INIT";
export const CORPORATE_USERS_BULK_LIST_SUCCESS =
  "CORPORATE_USERS_BULK_LIST_SUCCESS";
export const CORPORATE_USERS_BULK_LIST_FAIL = "CORPORATE_USERS_BULK_LIST_FAIL";

//Search Corporate Users
export const SEARCH_CORPORATE_USERS_INIT = "SEARCH_CORPORATE_USERS_INIT";
export const SEARCH_CORPORATE_USERS_SUCCESS = "SEARCH_CORPORATE_USERS_SUCCESS";
export const SEARCH_CORPORATE_USERS_FAIL = "SEARCH_CORPORATE_USERS_FAIL";

//Search Bank Users
export const SEARCH_BANK_USERS_INIT = "SEARCH_BANK_USERS_INIT";
export const SEARCH_BANK_USERS_SUCCESS = "SEARCH_BANK_USERS_SUCCESS";
export const SEARCH_BANK_USERS_FAIL = "SEARCH_BANK_USERS_FAIL";

//Update Corporate User
export const UPDATE_CORPORATE_USERS_INIT = "UPDATE_CORPORATE_USERS_INIT";
export const UPDATE_CORPORATE_USERS_SUCCESS = "UPDATE_CORPORATE_USERS_SUCCESS";
export const UPDATE_CORPORATE_USERS_FAIL = "UPDATE_CORPORATE_USERS_FAIL";

//Get Bank User by UserID
export const GET_BANK_USER_BY_USERID_INIT = "GET_BANK_USER_BY_USERID_INIT";
export const GET_BANK_USER_BY_USERID_SUCCESS =
  "GET_BANK_USER_BY_USERID_SUCCESS";
export const GET_BANK_USER_BY_USERID_FAIL = "GET_BANK_USER_BY_USERID_FAIL";

//Update Bank User By Bank ID
export const UPDATE_BANK_USER_BY_USERID_INIT =
  "UPDATE_BANK_USER_BY_USERID_INIT";
export const UPDATE_BANK_USER_BY_USERID_SUCCESS =
  "UPDATE_BANK_USER_BY_USERID_SUCCESS";
export const UPDATE_BANK_USER_BY_USERID_FAIL =
  "UPDATE_BANK_USER_BY_USERID_FAIL";

export const CLEARE_MESSAGE = "CLEARE_MESSAGE";

//Get VolMeters By Bannking ID
export const GET_VOLMETER_BY_BANKID_INIT = "GET_VOLMETER_BY_BANKID_INIT";
export const GET_VOLMETER_BY_BANKID_SUCCESS = "GET_VOLMETER_BY_BANKID_SUCCESS";
export const GET_VOLMETER_BY_BANKID_FAIL = "GET_VOLMETER_BY_BANKID_FAIL";

//Add Update Volmeter
export const ADD_UPDATE_VOLMTER_INIT = "ADD_UPDATE_VOLMTER_INIT";
export const ADD_UPDATE_VOLMTER_SUCCESS = "ADD_UPDATE_VOLMTER_SUCCESS";
export const ADD_UPDATE_VOLMTER_FAIL = "ADD_UPDATE_VOLMTER_FAIL";

//Update Volmeter By Dealer
export const UPDATE_VOLMETER_BY_DEALER_INIT = "UPDATE_VOLMETER_BY_DEALER_INIT";
export const UPDATE_VOLMETER_BY_DEALER_SUCCESS =
  "UPDATE_VOLMETER_BY_DEALER_SUCCESS";
export const UPDATE_VOLMETER_BY_DEALER_FAIL = "UPDATE_VOLMETER_BY_DEALER_FAIL";

// Update VolMeter Setting By Bank Id
export const UPDATE_VOLMETER_SETTING_BY_BANK_ID_INIT =
  "UPDATE_VOLMETER_SETTING_BY_BANK_ID_INIT";
export const UPDATE_VOLMETER_SETTING_BY_BANK_ID_SUCCESS =
  "UPDATE_VOLMETER_SETTING_BY_BANK_ID_SUCCESS";
export const UPDATE_VOLMETER_SETTING_BY_BANK_ID_FAIL =
  "UPDATE_VOLMETER_SETTING_BY_BANK_ID_FAIL";

//Get Volmeter Setting By Bank ID
export const GET_VOLMETER_SETTING_BY_BANK_ID_INIT =
  "GET_VOLMETER_SETTING_BY_BANK_ID_INIT";
export const GET_VOLMETER_SETTING_BY_BANK_ID_SUCCESS =
  "GET_VOLMETER_SETTING_BY_BANK_ID_INIT";
export const GET_VOLMETER_SETTING_BY_BANK_ID_FAIL =
  "GET_VOLMETER_SETTING_BY_BANK_ID_INIT";

//Get Corporate User By User ID
export const GET_CORPORATE_USER_BY_USERID_INIT =
  "GET_CORPORATE_USER_BY_USERID_INIT";
export const GET_CORPORATE_USER_BY_USERID_SUCCESS =
  "GET_CORPORATE_USER_BY_USERID_SUCCESS";
export const GET_CORPORATE_USER_BY_USERID_FAIL =
  "GET_CORPORATE_USER_BY_USERID_FAIL";

//Get All ROLES LIST
export const ROLE_LIST_INIT = "ROLE_LIST_INIT";
export const ROLE_LIST_SUCCESS = "ROLE_LIST_SUCCESS";
export const ROLE_LIST_FAIL = "ROLE_LIST_FAIL";

//Get All User ROLES LIST
export const GET_BANK_USER_ROLES_INIT = "GET_BANK_USER_ROLES_INIT";
export const GET_BANK_USER_ROLES_SUCCESS = "GET_BANK_USER_ROLES_SUCCESS";
export const GET_BANK_USER_ROLES_FAIL = "GET_BANK_USER_ROLES_FAIL";

//Get Counter Party Names
export const GET_COUNTER_PARTY_NAMES_INIT = "GET_COUNTER_PARTY_NAMES_INIT";
export const GET_COUNTER_PARTY_NAMES_SUCCESS =
  "GET_COUNTER_PARTY_NAMES_SUCCESS";
export const GET_COUNTER_PARTY_NAMES_FAIL = "GET_COUNTER_PARTY_NAMES_FAIL";

//Get All Instruments
export const GET_ALL_INSTRUMENTS_INIT = "GET_ALL_INSTRUMENTS_INIT";
export const GET_ALL_INSTRUMENTS_SUCCESS = "GET_ALL_INSTRUMENTS_SUCCESS";
export const GET_ALL_INSTRUMENTS_FAIL = "GET_ALL_INSTRUMENTS_FAIL";

//Get All Instrument Types
export const GET_ALL_INSTRUMENT_TYPES_INIT = "GET_ALL_INSTRUMENT_TYPES_INIT";
export const GET_ALL_INSTRUMENT_TYPES_SUCCESS =
  "GET_ALL_INSTRUMENT_TYPES_SUCCESS";
export const GET_ALL_INSTRUMENT_TYPES_FAIL = "GET_ALL_INSTRUMENT_TYPES_FAIL";

//Get User Settings
export const GET_USER_SETTINGS_INIT = "GET_USER_SETTINGS_INIT";
export const GET_USER_SETTINGS_SUCCESS = "GET_USER_SETTINGS_SUCCESS";
export const GET_USER_SETTINGS_FAIL = "GET_USER_SETTINGS_FAIL";

//Update user Settings
export const UPDATE_USER_SETTINGS_INIT = "UPDATE_USER_SETTINGS_INIT";
export const UPDATE_USER_SETTINGS_SUCCESS = "UPDATE_USER_SETTINGS_SUCCESS";
export const UPDATE_USER_SETTINGS_FAIL = "UPDATE_USER_SETTINGS_FAIL";

//Search All User Login History
export const SEARCH_ALL_USER_LOGIN_HISTORY_INIT =
  "SEARCH_ALL_USER_LOGIN_HISTORY_INIT";

export const SEARCH_ALL_USER_LOGIN_HISTORY_SUCCESS =
  "SEARCH_ALL_USER_LOGIN_HISTORY_SUCCESS";
export const SEARCH_ALL_USER_LOGIN_HISTORY_FAIL =
  "SEARCH_ALL_USER_LOGIN_HISTORY_FAIL";

//Get Market Time Settings
export const GET_MARKET_TIME_SETTINGS_INIT = "GET_MARKET_TIME_SETTINGS_INIT";
export const GET_MARKET_TIME_SETTINGS_SUCCESS =
  "GET_MARKET_TIME_SETTINGS_SUCCESS";
export const GET_MARKET_TIME_SETTINGS_FAIL = "GET_MARKET_TIME_SETTINGS_FAIL";

//Save Market Time Settings
export const SAVE_MARKET_TIME_SETTINGS_INIT = "SAVE_MARKET_TIME_SETTINGS_INIT";
export const SAVE_MARKET_TIME_SETTINGS_SECCESS =
  "SAVE_MARKET_TIME_SETTINGS_SECCESS";
export const SAVE_MARKET_TIME_SETTINGS_FAIL = "SAVE_MARKET_TIME_SETTINGS_FAIL";

export const USER_LOGOUT_INIT = "USER_LOGOUT_INIT";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";

export const GET_COUNTER_PARTY_LIST_INIT = "GET_COUNTER_PARTY_LIST_INIT";
export const GET_COUNTER_PARTY_LIST_SUCCESS = "GET_COUNTER_PARTY_LIST_SUCCESS";
export const GET_COUNTER_PARTY_LIST_FAIL = "GET_COUNTER_PARTY_LIST_FAIL";

//GetCorporatesWithStatus
export const GET_CORPORATES_WITH_STATUS_INTI =
  "GET_CORPORATES_WITH_STATUS_INTI";
export const GET_CORPORATES_WITH_STATUS_SUCCESS =
  "GET_CORPORATES_WITH_STATUS_SUCCESS";
export const GET_CORPORATES_WITH_STATUS_FAIL =
  "GET_CORPORATES_WITH_STATUS_FAIL";

//UpdateCorporateStatus
export const UPDATE_CORPORATE_STATUS_INIT = "UPDATE_CORPORATE_STATUS_INIT";
export const UPDATE_CORPORATE_STATUS_SUCCESS =
  "UPDATE_CORPORATE_STATUS_SUCCESS";
export const UPDATE_CORPORATE_STATUS_FAIL = "UPDATE_CORPORATE_STATUS_FAIL";

//GetCorporateTradeRights
export const GET_CORPORATE_TRADE_RIGHTS_INIT =
  "GET_CORPORATE_TRADE_RIGHTS_INIT";
export const GET_CORPORATE_TRADE_RIGHTS_SUCCESS =
  "GET_CORPORATE_TRADE_RIGHTS_SUCCESS";
export const GET_CORPORATE_TRADE_RIGHTS_FAIL =
  "GET_CORPORATE_TRADE_RIGHTS_FAIL";

//GetBranchesWithStatus
export const GET_BRANCHES_WITH_STATUS_INIT = "GET_BRANCHES_WITH_STATUS_INIT";
export const GET_BRANCHES_WITH_STATUS_SUCCESS =
  "GET_BRANCHES_WITH_STATUS_SUCCESS";
export const GET_BRANCHES_WITH_STATUS_FAIL = "GET_BRANCHES_WITH_STATUS_FAIL";

//GetBranchesWithStatus
export const UPDATE_BRANCH_STATUS_INIT = "UPDATE_BRANCH_STATUS_INIT";
export const UPDATE_BRANCH_STATUS_SUCCESS = "UPDATE_BRANCH_STATUS_SUCCESS";
export const UPDATE_BRANCH_STATUS_FAIL = "UPDATE_BRANCH_STATUS_FAIL";

//GetBranchTradeRights
export const GET_BRANCH_TRADE_RIGHTS_INIT = "GET_BRANCH_TRADE_RIGHTS_INIT";
export const GET_BRANCH_TRADE_RIGHTS_SUCCESS =
  "GET_BRANCH_TRADE_RIGHTS_SUCCESS";
export const GET_BRANCH_TRADE_RIGHTS_FAIL = "GET_BRANCH_TRADE_RIGHTS_FAIL";

//UpdateBranchTradeRights
export const UPDATE_BRANCH_TRADE_RIGHTS_INIT = "UPDATE_BRANCH_TRADE_RIGHT_INIT";
export const UPDATE_BRANCH_TRADE_RIGHT_SUCCESS =
  "UPDATE_BRANCH_TRADE_RIGHT_SUCCESS";
export const UPDATE_BRANCH_TRADE_RIGHT_FAIL = "UPDATE_BRANCH_TRADE_RIGHT_FAIL";

//UpdateBranchTradeRights
export const UPDATE_CORPORATE_TRADE_RIGHTS_INIT =
  "UPDATE_CORPORATE_TRADE_RIGHT_INIT";
export const UPDATE_CORPORATE_TRADE_RIGHT_SUCCESS =
  "UPDATE_CORPORATE_TRADE_RIGHT_SUCCESS";
export const UPDATE_CORPORATE_TRADE_RIGHT_FAIL =
  "UPDATE_CORPORATE_TRADE_RIGHT_FAIL";
export const UPDATE_CATEGORY_INIT = "UPDATE_CATEGORY_INIT";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAIL = "UPDATE_CATEGORY_FAIL";

export const UPDATE_BRANCH_CATEGORY_MAPPING_INIT =
  "UPDATE_BRANCH_CATEGORY_MAPPING_INIT";

export const UPDATE_BRANCH_CATEGORY_MAPPING_SUCCESS =
  "UPDATE_BRANCH_CATEGORY_MAPPING_SUCCESS";

export const UPDATE_BRANCH_CATEGORY_MAPPING_FAILED =
  "UPDATE_BRANCH_CATEGORY_MAPPING_FAILED";

export const DELETE_CATEGORY_MODAL = "DELETE_CATEGORY_MODAL";

export const GET_SPOT_SPREAD_FOR_CATEGORY_INIT =
  "GET_SPOT_SPREAD_FOR_CATEGORY_INIT";
export const GET_SPOT_SPREAD_FOR_CATEGORY_SUCCESS =
  "GET_SPOT_SPREAD_FOR_CATEGORY_SUCCESS";
export const GET_SPOT_SPREAD_FOR_CATEGORY_FAIL =
  "GET_SPOT_SPREAD_FOR_CATEGORY_FAIL";

export const GET_CROSS_RATE_SPREADS_FOR_CATEGORY_INIT =
  "GET_CROSS_RATE_SPREADS_FOR_CATEGORY_INIT";
export const GET_CROSS_RATE_SPREADS_FOR_CATEGORY_SUCCESS =
  "GET_CROSS_RATE_SPREADS_FOR_CATEGORY_SUCCESS";
export const GET_CROSS_RATE_SPREADS_FOR_CATEGORY_FAIL =
  "GET_CROSS_RATE_SPREADS_FOR_CATEGORY_FAIL";

export const GET_TENOR_WISE_FORWARD_SPREADS_FOR_CATEGORY_INIT =
  "GET_TENOR_WISE_FORWARD_SPREADS_FOR_CATEGORY_INIT";
export const GET_TENOR_WISE_FORWARD_SPREADS_FOR_CATEGORY_SUCCESS =
  "GET_TENOR_WISE_FORWARD_SPREADS_FOR_CATEGORY_SUCCESS";
export const GET_TENOR_WISE_FORWARD_SPREADS_FOR_CATEGORY_FAIL =
  "GET_TENOR_WISE_FORWARD_SPREADS_FOR_CATEGORY_FAIL";

export const GET_ALL_CORPORATES_DATA_INIT = "GET_ALL_CORPORATES_DATA_INIT";
export const GET_ALL_CORPORATES_DATA_SUCCESS =
  "GET_ALL_CORPORATES_DATA_SUCCESS";
export const GET_ALL_CORPORATES_DATA_FAIL = "GET_ALL_CORPORATES_DATA_FAIL";

export const GET_TENOR_WISE_FE_DISCOUNTING_SPREADS_FOR_CATEGORY_INIT =
  "GET_TENOR_WISE_FE_DISCOUNTING_SPREADS_FOR_CATEGORY_INIT";
export const GET_TENOR_WISE_FE_DISCOUNTING_SPREADS_FOR_CATEGORY_SUCCESS =
  "GET_TENOR_WISE_FE_DISCOUNTING_SPREADS_FOR_CATEGORY_SUCCESS";
export const GET_TENOR_WISE_FE_DISCOUNTING_SPREADS_FOR_CATEGORY_FAIL =
  "GET_TENOR_WISE_FE_DISCOUNTING_SPREADS_FOR_CATEGORY_FAIL";
